version: '3.8'

services:
  backend:
    build:
      context: ./BookShop.API
      dockerfile: Dockerfile
    ports:
      - "5045:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - my-network

  frontend:
    build:
      context: ./BookShop.Client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - "27020:27020"
    command: ["mongod", "--port", "27020"]
    volumes:
      - ./mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:
